repos:
  - repo: local
    hooks:
      - id: validate-jira-commit-msg
        name: "Valida mensagem de commit TRK-XXX"
        language: system
        entry: |
          bash -c '
            commit_msg_file="$1";
            first_line=$(head -n 1 "$commit_msg_file");
            expected_pattern="^(TRK-[0-9]+ - (feat|fix|release|hotfix): )";
            if [[ ! "$first_line" =~ $expected_pattern ]]; then
                echo "";
                echo "====================================================================================";
                echo "  ERRO: Sua mensagem de commit não segue o padrão exigido.";
                echo "  A mensagem DEVE começar com uma das seguintes opções:";
                echo "  - TRK-XXX - feat: Sua mensagem";
                echo "  - TRK-XXX - fix: Sua mensagem";
                echo "  - TRK-XXX - release: Sua mensagem";
                echo "  - TRK-XXX - hotfix: Sua mensagem";
                echo "  Onde 'XXX' é o número da sua tarefa do Jira (ex: TRK-106).";
                echo "====================================================================================";
                echo "";
                exit 1;
            fi;
            exit 0;
          '
        args: [".git/COMMIT_EDITMSG"]
        stages: [commit-msg]