# Conteúdo do arquivo: .pre-commit-config.yaml
# Define a versão mínima exigida do pre-commit
minimum_pre_commit_version: '3.0.0'

repos:
  - repo: local
    hooks:
      - id: validate-jira-commit-msg
        name: "Valida mensagem de commit TRK-XXX"
        # O 'language: system' vai usar o shell nativo (bash no Git Bash)
        language: system
        # Use o operador literal '|' para strings multilinha
        # O 'entry' é o comando shell que será executado para validar a mensagem
        # O '$1' refere-se ao arquivo temporário da mensagem de commit
        entry: |
          bash -c '
            commit_msg_file="$1";
            first_line=$(head -n 1 "$commit_msg_file");
            expected_pattern="^(TRK-[0-9]+ - (feat|fix|release|hotfix): )";
            if [[ ! "$first_line" =~ $expected_pattern ]]; then
                echo "";
                echo "====================================================================================";
                echo "  ERRO: Sua mensagem de commit não segue o padrão exigido.";
                echo "  A mensagem DEVE começar com uma das seguintes opções:";
                echo "  - TRK-XXX - feat: Sua mensagem";
                echo "  - TRK-XXX - fix: Sua mensagem";
                echo "  - TRK-XXX - release: Sua mensagem";
                echo "  - TRK-XXX - hotfix: Sua mensagem";
                echo "  Onde 'XXX' é o número da sua tarefa do Jira (ex: TRK-106).";
                echo "====================================================================================";
                echo "";
                exit 1;
            fi;
            exit 0;
          '
        # O '$1' no script 'entry' acima será o caminho para este arquivo
        args: [".git/COMMIT_EDITMSG"]
        # Este hook é executado no estágio 'commit-msg' do Git
        stages: [commit-msg]